version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: nft_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  django_app:
    build:
      context: .
    container_name: nft_django
    depends_on:
      - postgres
    volumes:
      - ./static:/root/projects/var/www/nft/static
      - ./media:/root/projects/var/www/nft/media
    env_file:
      - .env
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn -b 0.0.0.0:8000 my_project.wsgi:application"
    ports:
      - "8080:8000"

  nginx:
    build:
      dockerfile: Dockerfile.nginx
      context: .
    container_name: nft_nginx
    depends_on:
      - django_app
    ports:
      - "90:80"
      - "444:443"
    volumes:
      - ./static:/root/projects/var/www/nft/static
      - ./media:/root/projects/var/www/nft/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

volumes:
  postgres_data:
  certs:
  vhost:
  html:
