version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: nft_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  django_gunicorn:
    build:
      context: .
    container_name: nft_django_gunicorn
    depends_on:
      - postgres
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - .:/app  # монтируем текущую директорию на хосте в контейнер
      - static:/static  # монтируем статические файлы
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn my_project.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8780:8000"

  nginx:
    build:
      dockerfile: Dockerfile.nginx
      context: .
    container_name: nft_nginx
    depends_on:
      - django_gunicorn
    ports:
      - "83:80"
    volumes:
      - static:/static  # монтируем статические файлы
      - ./nginx.conf:/etc/nginx/nginx.conf  # конфиг Nginx

volumes:
  postgres_data:
  static:
