version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: nft_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  django:
    build:
      context: .
    container_name: nft_django
    depends_on:
      - postgres
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - .:/root/projects/NFT  # монтируем текущую директорию на хосте в контейнер
      - /root/projects/var/www/nft/static  # монтируем директорию для статических файлов
      - /root/projects/var/www/nft/media  # монтируем директорию для медиа файлов
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn -b 0.0.0.0:8000 my_project.wsgi:application"
    ports:
      - "8090:8000"

  nginx:
    build:
      dockerfile: Dockerfile.nginx
      context: .
    container_name: nft_nginx
    depends_on:
      - django
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /root/projects/var/www/nft/static:/app/static  # монтируем статику
      - /root/projects/var/www/nft/media:/app/media  # монтируем медиа файлы
      - ./nginx.conf:/etc/nginx/nginx.conf  # добавляем конфиг Nginx (если нужно)

volumes:
  postgres_data:
