# Используем официальный образ Nginx
FROM nginx:alpine

# Копируем конфиг Nginx в контейнер
COPY nginx.conf /etc/nginx/nginx.conf

# Копируем статичные и медиа-файлы
COPY ./static /app/static
COPY ./media /app/media

# Открываем порты
EXPOSE 80 443
