services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8780:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "83:80"
    depends_on:
      - django_gunicorn

volumes:
  static: