version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 my_project.wsgi:application
    volumes:
      - /root/projects/NFT/static:/root/var/www/nft/static
      - /root/projects/NFT/media:/root/var/www/nft/media
      - /root/projects/NFT/logs:/root/var/www/nft/logs  # Добавляем монтирование для логов

    ports:
      - "8082:8000"
    env_file:
      - .env
    networks:
      - database_network
      - https_network

volumes:
  static:
  media:

networks:
  database_network:
    name: ${DATABASE_NETWORK}
    external: true
  https_network:
    name: ${HTTPS_NETWORK}
    external: true
