version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 my_project.wsgi:application
    volumes:
      - /root/projects/NFT:/root/projects/NFT
      - static_volume:/root/projects/var/www/nft/static
      - media_volume:/root/projects/var/www/nft/media
      - log_volume:/root/projects/var/www/nft/logs
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

volumes:
  postgres_data:
  static_volume:
  media_volume:
  log_volume:
