version: "3.9"

services:
  web:
    build:
      context: .
    container_name: django_web
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn my_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web_network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - web_network

volumes:
  postgres_data:

networks:
  web_network:
    driver: bridge
