services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nft_network

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 my_project.wsgi:application
    volumes:
      - /root/var/www/nft/static:/root/var/www/nft/static
      - /root/var/www/nft/media:/root/var/www/nft/media
      - /root/var/www/nft/logs:/root/var/www/nft/logs
    ports:
      - "8082:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - nft_network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8080:80"
      - "8443:443"
      - "8181:81"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - nft_network

volumes:
  postgres_data:
  nginx_data:
  nginx_letsencrypt:

networks:
  nft_network:
