version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 my_project.wsgi:application
    volumes:
      - static:/root/var/www/nft/static
      - media:/root/var/www/nft/media
      - /root/var/www/nft/logs:/root/var/www/nft/logs
    ports:
      - "8082:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - database_network
      - https_network

  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "${PORT}:81"
      - "443:443"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
      - static:/root/var/www/nft/static
      - media:/root/var/www/nft/media
    networks:
      - https_network

volumes:
  static:
  media:
  data:
  letsencrypt:

networks:
  database_network:
    name: ${DATABASE_NETWORK}
    external: true
  https_network:
    name: ${HTTPS_NETWORK}
    external: true
