version: '3.8'

services:
  web:
    build: .
    container_name: nft_web
    command: gunicorn my_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/root/projects/var/www/nft/static
      - ./media:/root/projects/var/www/nft/media
    env_file:
      - .env
    ports:
      - "8090:8000"
    depends_on:
      - db
    environment:
      - WSGI_MODULE=${WSGI_MODULE}

  db:
    image: postgres:15
    container_name: nft_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nft_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/root/projects/var/www/nft/static
      - ./media:/root/projects/var/www/nft/media
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  postgres_data:
