services:
  nft:
    build: .
    restart: always
    container_name: nft-dev
    volumes:
      - .:/root/projects/NFT
      - ./static:/root/projects/var/www/nft/static  # Статика
      - ./media:/root/projects/var/www/nft/media    # Медиа


    ports:
      - "8002:8000"
    env_file:
      - .env
    networks:
      - https
      - database
  db:  # Добавляем сервис для базы данных
    image: postgres:13  # Используем официальный образ PostgreSQL
    container_name: nft-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - database
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Храним данные PostgreSQL

networks:
  https:
    driver: bridge
  database:
    driver: bridge

volumes:
  postgres_data: {}  # Создаем том для хранения данных PostgreSQL
