# Generated by Django 3.2.11 on 2024-11-12 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d+$', 'Введите только цифры и, при необходимости, знак + в начале для Telegram.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tiktok_link',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Введите только латинские буквы и цифры для TikTok.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d+$', 'Введите только цифры и, при необходимости, знак + в начале для WhatsApp.')]),
        ),
    ]
